name: fit3d
channels:
  - conda-forge
  - pytorch
  - defaults
  - pytorch3d
  - open3d-admin
  - anaconda
dependencies:
  - pip=21.1.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - pandas=1.3.1
  - python=3.7.6
  - pytorch=1.7.1
  - tensorboardx=2.2
  - cudatoolkit=10.2.89
  - torchvision=0.8.2
  - einops=0.3.0
  - pytorch3d=0.4.0
  - tqdm=4.61.2
  - trimesh=3.9.24
  - joblib=1.0.1
  - open3d=0.13.0
  - pip:
    - h5py==2.9.0
    - chumpy==0.70
    - smplx==0.1.28
